# Generated by Django 4.2.4 on 2023-08-15 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_description_alter_task_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.BooleanField(choices=[(True, 'Completed'), (False, 'Uncompleted')], default=0),
        ),
    ]
