# Generated by Django 4.2.4 on 2023-08-17 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_task_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.BooleanField(choices=[(True, 'Completed'), (False, 'Uncompleted')], default=0, null=True),
        ),
    ]
